#!/usr/bin/env python3
"""Generate large .conv training sets for TheBrain v13 easytrain."""
import os
import glob
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "conv", "generated")
os.makedirs(OUT, exist_ok=True)


def write_conv(path, pairs):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Auto-generated by gen_conv_corpus.py\n")
        for u, a in pairs:
            u = " ".join(u.split())
            a = " ".join(a.split())
            if not u or not a:
                continue
            f.write(f"U: {u}\nA: {a}\n\n")


def gen_c89_bulk():
    topics = [
        ("What is a pointer in C?", "A pointer stores an address. Declare with asterisk, take address with ampersand, read value with asterisk dereference."),
        ("What is malloc?", "malloc allocates heap memory. Always check for NULL and free with free() when done. Example: p = (int*)malloc(n * sizeof(int));"),
        ("How do I open a file in C89?", "Use FILE* fp = fopen(\"name.txt\", \"r\"); read with fgets or fread; close with fclose(fp)."),
        ("What is struct in C?", "struct groups related fields. Example: struct Point { int x; int y; }; Access with dot or arrow for pointers."),
        ("Explain for loop in C89", "for (i = 0; i < n; i++) { body; } In C89 declare loop variables at the start of the block."),
        ("What is header file?", "A .h file declares functions and types. The .c file implements them. Include with #include \"myfile.h\"."),
        ("How to write Hello World in C89?", "#include <stdio.h> int main(void) { puts(\"Hello\"); return 0; }"),
        ("What is NULL?", "NULL is a null pointer constant. Dereferencing NULL causes undefined behavior. Always test pointers before use."),
        ("What is string in C?", "C strings are char arrays ending with '\\0'. Use strcpy, strncpy, strlen from string.h carefully with buffer sizes."),
        ("What is enum?", "enum creates named integer constants. Example: enum Color { RED, GREEN, BLUE };"),
    ]
    langs = [
        ("Python", "Python uses indentation. Lists are mutable, tuples are not. Use def for functions."),
        ("Java", "Java runs on JVM. Every file can have one public class matching the filename."),
        ("JavaScript", "JavaScript runs in browsers and Node. let and const are block scoped in modern JS."),
        ("Pascal", "Pascal uses begin/end blocks and strong typing common in teaching languages."),
        ("Assembly", "Assembly maps directly to CPU instructions. Registers and memory addressing vary by architecture."),
        ("C++", "C++ extends C with classes, references, and RAII. Not used in strict C89 projects."),
        ("Rust", "Rust focuses on memory safety without garbage collection using ownership rules."),
        ("Go", "Go has goroutines for concurrency and garbage collection with static typing."),
        ("PHP", "PHP is common for web servers. Variables start with dollar sign."),
        ("SQL", "SQL queries relational databases. SELECT reads rows, INSERT adds, UPDATE changes, DELETE removes."),
    ]
    pairs = []
    for q, a in topics:
        pairs.append((q, a))
        pairs.append((q.replace("?", " in simple terms?"), a))
    for name, desc in langs:
        pairs.append((f"What is {name}?", desc))
        pairs.append((f"Tell me about {name}", desc))
    for i in range(1, 51):
        pairs.append((f"What is {i} plus {i}?", f"{i} plus {i} equals {i + i}."))
        pairs.append((f"Compute {i}+{i+1}", f"The sum is {i + i + 1}."))
    write_conv(os.path.join(OUT, "programming_bulk.conv"), pairs)


def gen_from_c_sources():
    pairs = []
    for folder in ("safe", "dangerous"):
        pat = os.path.join(ROOT, "data", folder, "*.c")
        for path in glob.glob(pat):
            name = os.path.basename(path)
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as f:
                    src = f.read(1200)
            except OSError:
                continue
            src = src.replace("\r\n", "\n").replace("\n", " ")
            src = " ".join(src.split())
            if len(src) < 40:
                continue
            pairs.append((
                f"Explain the C source file {name}",
                f"This file {name} contains C code. Key idea: {src[:400]}..."
            ))
            pairs.append((
                f"What does {name} demonstrate?",
                f"It demonstrates patterns in {name}. Summary: {src[:350]}..."
            ))
    write_conv(os.path.join(OUT, "code_from_c_files.conv"), pairs)


def gen_multilingual():
    ar = [
        ("مرحبا", "مرحبا. كيف يمكنني مساعدتك؟"),
        ("كيف حالك؟", "أنا بخير، شكرا. ماذا تريد أن تسأل؟"),
        ("من أنت؟", "أنا TheBrain، مساعد محادثة مدرب على ملفات .conv."),
        ("تكلم معي بالعربية", "بالطبع. اكتب بالعربية وسأحاول الرد بالعربية."),
        ("ما ناتج 5+7؟", "خمسة زائد سبعة يساوي اثني عشر."),
        ("اكتب برنامج C بسيط", "مثال: #include <stdio.h> int main(void){ puts(\"Hello\"); return 0; }"),
        ("ما هو PE؟", "PE هو تنسيق ملفات Windows التنفيذية ويحتوي على headers وأقسام مثل .text و .data."),
        ("شكرا", "العفو. أنا هنا إذا احتجت مساعدة."),
    ]
    fr = [
        ("Bonjour", "Bonjour. Comment puis-je vous aider ?"),
        ("Comment vas-tu?", "Je vais bien, merci. Que voulez-vous savoir ?"),
        ("Parle francais", "Oui, vous pouvez ecrire en francais et je repondrai en francais."),
        ("Qu'est-ce que 8+3?", "Huit plus trois egale onze."),
        ("Ecris un programme C", "Exemple: #include <stdio.h> int main(void){ puts(\"Bonjour\"); return 0; }"),
    ]
    en = [
        ("Can you talk in Arabic?", "Yes. Type in Arabic and I will reply in Arabic when possible."),
        ("Can you talk in French?", "Yes. Type in French and I will reply in French when possible."),
        ("Write a C program please", "Here is a short C89 example: #include <stdio.h> int main(void){ puts(\"Hello\"); return 0; }"),
        ("Are you able to code?", "I can explain and show small C89 examples. I am trained on Q&A, not a compiler."),
        ("I don't understand", "Tell me what part is unclear and I will explain step by step in simpler words."),
    ]
    write_conv(os.path.join(OUT, "multilingual_ar.conv"), ar)
    write_conv(os.path.join(OUT, "multilingual_fr.conv"), fr)
    write_conv(os.path.join(OUT, "multilingual_en.conv"), en)


def gen_malware_chat():
    pairs = []
    snippets = [
        ("What is ransomware?", "Ransomware encrypts victim files and demands payment for decryption keys."),
        ("What is a trojan?", "A trojan disguises itself as legitimate software while performing hidden malicious actions."),
        ("What is entropy in PE analysis?", "High entropy often indicates packing or encryption in a PE section."),
        ("What is VirtualAlloc used for?", "VirtualAlloc allocates memory. Malware may use it for shellcode or injection."),
        ("What is YARA?", "YARA matches patterns in files using rules to identify malware families."),
        ("How to analyze a suspicious EXE?", "Check PE headers, imports, sections, strings, entropy, and run in an isolated sandbox."),
    ]
    for q, a in snippets:
        pairs.append((q, a))
        for i in range(5):
            pairs.append((f"{q} (explain simply)", a))
    write_conv(os.path.join(OUT, "malware_chat_bulk.conv"), pairs)


def main():
    gen_c89_bulk()
    gen_from_c_sources()
    gen_multilingual()
    gen_malware_chat()
    n = len(glob.glob(os.path.join(OUT, "*.conv")))
    print(f"Generated {n} files in {OUT}")


if __name__ == "__main__":
    main()
